Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "manager1" do |manager|
    manager.vm.hostname = "manager1"
    manager.vm.network "private_network", ip: "192.168.56.10"
  
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
      vb.name = "DO7-manager1"
    end
    
    manager.vm.network "forwarded_port", guest: 80, host: 8080
    manager.vm.network "forwarded_port", guest: 9000, host: 9000

    manager.vm.synced_folder ".", "/app", type: "rsync"
    manager.vm.synced_folder "./tmp", "/app/tmp", type: "virtualbox"

    manager.vm.provision "shell", path: "./scripts/install-docker.sh"
    manager.vm.provision "shell", path: "./scripts/init-swarm.sh"
  end

  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"
    worker.vm.network "private_network", ip: "192.168.56.11"
  
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
      vb.name = "DO7-worker1"
    end
    
    worker.vm.synced_folder ".", "/app", type: "rsync"
    worker.vm.synced_folder "./tmp", "/app/tmp", type: "virtualbox"

    worker.vm.provision "shell", path: "./scripts/install-docker.sh"
    worker.vm.provision "shell", path: "./scripts/join-swarm.sh"
  end

  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"
    worker.vm.network "private_network", ip: "192.168.56.12"
  
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
      vb.name = "DO7-worker2"
    end
    
    worker.vm.synced_folder ".", "/app", type: "rsync"
    worker.vm.synced_folder "./tmp", "/app/tmp", type: "virtualbox"

    worker.vm.provision "shell", path: "./scripts/install-docker.sh"
    worker.vm.provision "shell", path: "./scripts/join-swarm.sh"
  end
end